apiVersion: apps/v1
kind: Deployment
metadata:
  name: solar-system

spec:
  replicas: 2

  selector:
    matchLabels:
      app: solar-system

  template:
    metadata:
      labels:
        app: solar-system

    spec:
      containers:
      - name: solar-system
        image: 211125513710.dkr.ecr.us-east-1.amazonaws.com/solar-system:ea07e02ea25e1e90d4db086b0ff8dd1578ea37e6
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
