apiVersion: apps/v1
kind: Deployment
metadata:
  name: solar-system

spec:
  replicas: 2

  selector:
    matchLabels:
      app: solar-system

  template:
    metadata:
      labels:
        app: solar-system

    spec:
      containers:
      - name: solar-system
        image: 455986776549.dkr.ecr.us-east-1.amazonaws.com/solar-system:24cb8c7a02c37be0c398554549cc4a0602196dd4
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
